package com.cipherradar.sonarqube;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import org.sonar.api.batch.fs.FileSystem;
import org.sonar.api.batch.fs.InputFile;
import org.sonar.api.batch.sensor.Sensor;
import org.sonar.api.batch.sensor.SensorContext;
import org.sonar.api.batch.sensor.SensorDescriptor;
import org.sonar.api.batch.sensor.issue.NewExternalIssue;
import org.sonar.api.batch.sensor.issue.NewIssueLocation;
import org.sonar.api.rules.RuleType;
import org.sonar.api.batch.rule.Severity;
import org.sonar.api.utils.log.Logger;
import org.sonar.api.utils.log.Loggers;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * SonarQube sensor that reads CipherRadar scan output and imports findings
 * as external issues.
 *
 * <p>Two input formats are supported:
 * <ol>
 *   <li><strong>SonarQube Generic Issue format</strong> — reads from the file specified
 *       by the {@code sonar.cipherradar.reportPath} property (default:
 *       {@code sonar-generic-issue-report.json}). Generated by
 *       {@code cradar scan --format sonarqube-generic}.</li>
 *   <li><strong>SARIF 2.1</strong> — reads from file(s) specified by
 *       {@code sonar.sarifReportPaths} (native SonarQube SARIF support).
 *       Generated by {@code cradar scan --format sarif}.</li>
 * </ol>
 *
 * <p>This sensor focuses on the generic issue format; SARIF import is handled
 * natively by SonarQube 10+ when {@code sonar.sarifReportPaths} is set.
 */
public class CipherRadarSensor implements Sensor {

    private static final Logger LOG = Loggers.get(CipherRadarSensor.class);

    /** Default report file name for the generic issue format. */
    private static final String DEFAULT_REPORT_PATH = "sonar-generic-issue-report.json";

    /** SonarQube analysis property to override the report file location. */
    private static final String REPORT_PATH_PROPERTY = "sonar.cipherradar.reportPath";

    private static final String ENGINE_ID = "cipherradar";

    private final Gson gson = new Gson();

    @Override
    public void describe(SensorDescriptor descriptor) {
        descriptor.name("CipherRadar CBOM Sensor")
                .onlyWhenConfiguration(config ->
                        config.hasKey(REPORT_PATH_PROPERTY)
                                || Files.exists(resolveDefaultReportPath(config)));
    }

    @Override
    public void execute(SensorContext context) {
        String reportPathStr = context.config().get(REPORT_PATH_PROPERTY)
                .orElse(DEFAULT_REPORT_PATH);

        Path reportPath = context.fileSystem().baseDir().toPath().resolve(reportPathStr);

        if (!Files.exists(reportPath)) {
            LOG.info("CipherRadar report not found at {}, skipping.", reportPath);
            return;
        }

        LOG.info("CipherRadar: importing findings from {}", reportPath);

        try {
            String json = Files.readString(reportPath);
            importGenericIssues(context, json);
        } catch (IOException e) {
            LOG.error("CipherRadar: failed to read report file: {}", e.getMessage());
        }
    }

    // -----------------------------------------------------------------------
    // Generic issue format parser
    // -----------------------------------------------------------------------

    /**
     * Parse the SonarQube Generic Issue Import format and create external issues.
     *
     * <p>Expected JSON structure:
     * <pre>{@code
     * {
     *   "issues": [
     *     {
     *       "engineId": "cipherradar",
     *       "ruleId": "cbom-weak-hash",
     *       "severity": "CRITICAL",
     *       "type": "VULNERABILITY",
     *       "primaryLocation": {
     *         "message": "MD5 is a deprecated hash algorithm",
     *         "filePath": "src/main/java/Crypto.java",
     *         "textRange": {
     *           "startLine": 10,
     *           "startColumn": 5,
     *           "endLine": 10,
     *           "endColumn": 30
     *         }
     *       }
     *     }
     *   ]
     * }
     * }</pre>
     */
    private void importGenericIssues(SensorContext context, String json) {
        JsonObject root = gson.fromJson(json, JsonObject.class);
        JsonArray issues = root.getAsJsonArray("issues");

        if (issues == null || issues.isEmpty()) {
            LOG.info("CipherRadar: no issues found in report.");
            return;
        }

        FileSystem fs = context.fileSystem();
        int imported = 0;
        int skipped = 0;

        for (JsonElement element : issues) {
            JsonObject issue = element.getAsJsonObject();

            String engineId = getStringOrDefault(issue, "engineId", ENGINE_ID);
            if (!ENGINE_ID.equals(engineId)) {
                continue;
            }

            String ruleId = getStringOrDefault(issue, "ruleId", "cbom-crypto-detected");
            String severityStr = getStringOrDefault(issue, "severity", "INFO");
            String typeStr = getStringOrDefault(issue, "type", "CODE_SMELL");

            JsonObject primaryLocation = issue.getAsJsonObject("primaryLocation");
            if (primaryLocation == null) {
                skipped++;
                continue;
            }

            String message = getStringOrDefault(primaryLocation, "message", "CipherRadar finding");
            String filePath = getStringOrDefault(primaryLocation, "filePath", null);

            if (filePath == null) {
                skipped++;
                continue;
            }

            InputFile inputFile = fs.inputFile(fs.predicates().hasPath(filePath));
            if (inputFile == null) {
                // Try relative path resolution
                inputFile = fs.inputFile(fs.predicates().hasRelativePath(filePath));
            }
            if (inputFile == null) {
                LOG.debug("CipherRadar: file not found in SonarQube index: {}", filePath);
                skipped++;
                continue;
            }

            try {
                NewExternalIssue externalIssue = context.newExternalIssue()
                        .engineId(ENGINE_ID)
                        .ruleId(ruleId)
                        .type(parseRuleType(typeStr))
                        .severity(parseSeverity(severityStr));

                NewIssueLocation location = externalIssue.newLocation()
                        .on(inputFile)
                        .message(message);

                // Text range (optional)
                JsonObject textRange = primaryLocation.getAsJsonObject("textRange");
                if (textRange != null) {
                    int startLine = getIntOrDefault(textRange, "startLine", 1);
                    int startColumn = getIntOrDefault(textRange, "startColumn", 0);
                    int endLine = getIntOrDefault(textRange, "endLine", startLine);
                    int endColumn = getIntOrDefault(textRange, "endColumn", 0);

                    if (endColumn > 0) {
                        location.at(inputFile.newRange(startLine, startColumn, endLine, endColumn));
                    } else {
                        location.at(inputFile.selectLine(startLine));
                    }
                }

                externalIssue.at(location);
                externalIssue.save();
                imported++;
            } catch (Exception e) {
                LOG.warn("CipherRadar: failed to import issue for {}: {}",
                        filePath, e.getMessage());
                skipped++;
            }
        }

        LOG.info("CipherRadar: imported {} issues, skipped {} issues.", imported, skipped);
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private static Path resolveDefaultReportPath(org.sonar.api.config.Configuration config) {
        String path = config.get(REPORT_PATH_PROPERTY).orElse(DEFAULT_REPORT_PATH);
        return Paths.get(path);
    }

    private static String getStringOrDefault(JsonObject obj, String key, String defaultValue) {
        JsonElement el = obj.get(key);
        if (el != null && !el.isJsonNull()) {
            return el.getAsString();
        }
        return defaultValue;
    }

    private static int getIntOrDefault(JsonObject obj, String key, int defaultValue) {
        JsonElement el = obj.get(key);
        if (el != null && !el.isJsonNull()) {
            return el.getAsInt();
        }
        return defaultValue;
    }

    private static RuleType parseRuleType(String type) {
        try {
            return RuleType.valueOf(type);
        } catch (IllegalArgumentException e) {
            return RuleType.CODE_SMELL;
        }
    }

    private static Severity parseSeverity(String severity) {
        try {
            return Severity.valueOf(severity);
        } catch (IllegalArgumentException e) {
            return Severity.INFO;
        }
    }
}
