import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '../client.ts';
import type { Remediation } from '@/mocks/data/remediation.ts';

/**
 * Fetch cached remediation for a finding.
 * Real API endpoint: GET /api/v1/findings/:findingId/remediation
 * Falls back to mock data if endpoint is not ready.
 */
export function useRemediation(findingId: string | null) {
  return useQuery<Remediation | undefined>({
    queryKey: ['remediation', findingId],
    queryFn: async () => {
      try {
        const data = await apiClient<Remediation>(`/findings/${findingId!}/remediation`);
        if (data) return data;
      } catch {
        const { getRemediationForFinding } = await import('@/mocks/data/remediation.ts');
        return getRemediationForFinding(findingId!);
      }
    },
    staleTime: 60_000,
    enabled: !!findingId,
  });
}

/**
 * Request a new remediation generation for a finding (requires consent).
 * Real API endpoint: POST /api/v1/findings/:findingId/remediation
 */
export function useRequestRemediation() {
  const queryClient = useQueryClient();

  return useMutation<Remediation, Error, { findingId: string }>({
    mutationFn: async ({ findingId }) => {
      try {
        return await apiClient<Remediation>(`/findings/${findingId}/remediation`, {
          method: 'POST',
          body: { consent: true },
        });
      } catch {
        // Mock: simulate generation delay and return mock data
        await new Promise((resolve) => setTimeout(resolve, 1500));
        const { getRemediationForFinding } = await import(
          '@/mocks/data/remediation.ts'
        );
        const existing = getRemediationForFinding(findingId);
        if (existing) return existing;
        // Return a generic remediation for findings without mock data
        const fallback: Remediation = {
          id: `rem-gen-${findingId}`,
          findingId,
          confidence: 'medium',
          provider: 'anthropic',
          explanation:
            'AI-generated remediation suggestion. Review carefully before applying.',
          diff: {
            originalCode: '// Original code not available in mock mode',
            fixedCode: '// Fixed code will be generated by the LLM backend',
          },
          createdAt: new Date().toISOString(),
        };
        return fallback;
      }
    },
    onSuccess: (_data, variables) => {
      void queryClient.invalidateQueries({
        queryKey: ['remediation', variables.findingId],
      });
    },
  });
}
