package pdf

import (
	"github.com/johnfercher/maroto/v2/pkg/components/line"
	"github.com/johnfercher/maroto/v2/pkg/components/text"
	"github.com/johnfercher/maroto/v2/pkg/consts/align"
	"github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	"github.com/johnfercher/maroto/v2/pkg/core"
	"github.com/johnfercher/maroto/v2/pkg/props"

	"github.com/nk-sentinel/cipherradar/cli/internal/output"
)

// addFooter renders the report footer (CipherRadar version, generation note).
// Extracted from cli/internal/output/pdf.go addFooterNote.
func addFooter(m core.Maroto) {
	m.AddRows(line.NewRow(2, props.Line{
		Color:     ColorLightGray,
		Thickness: 0.3,
	}))

	m.AddRow(3)

	m.AddRow(5,
		text.NewCol(12, "Generated by CipherRadar v"+output.AppVersion+" — https://github.com/nk-sentinel/cipherradar", props.Text{
			Size:  7,
			Align: align.Center,
			Color: ColorInfo,
		}),
	)

	m.AddRow(5,
		text.NewCol(12, "This report is for informational purposes. Verify findings before making compliance decisions.", props.Text{
			Size:  7,
			Align: align.Center,
			Color: ColorInfo,
			Style: fontstyle.Italic,
		}),
	)
}
