package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

// Embedded templates live here (not in //go:embed) so downstream
// forks can tweak wording without a rebuild dance. They are small enough
// that string literals are clearer than a separate asset file.
const cradarYMLTemplate = `# .cradar.yml — CipherRadar CLI configuration
# Generated by 'cradar init'. Every key is optional; uncomment what you need.

# Portal integration (cradar scan --push).
# api_url: "https://cipherradar.company.com/api/v1"
# api_key_env: "CRADAR_API_KEY"   # read the key from this env var
# project: "my-service"
# group: "platform/backend"

# Default output format when --format is unset and stdout has no extension
# to dispatch on. Values: cyclonedx-json, sarif, text, table, pdf,
# sonarqube-generic. Omit to use TTY-aware defaults (text / cyclonedx-json).
# default_format: cyclonedx-json

# Scan passes: 1 = AST (fast, no external tools), 2 = OpenGrep taint.
# passes: [1, 2]

# Rule-lifecycle filters — CLI flags always override these values.
# rule_filters:
#   categories: [inventory, security]
#   include_experimental: false
#   include_noisy: false

# Custom wrapper functions mapped to CBOM asset types. Example below maps
# mycompany.crypto.encrypt(key, data, algo) to an algorithm finding.
# custom_wrappers:
#   - name: "mycompany.crypto.encrypt"
#     language: "python"
#     type: "algorithm"
#     severity: "info"
#     parameters:
#       key: 0
#       algorithm: 2
`

const policyYMLTemplate = `# policy.cradar.yml — CipherRadar policy rules
# Generated by 'cradar init'. Check in alongside your CBOM output and run
# 'cradar policy check cbom.json --policy policy.cradar.yml' in CI.

rules:
  - id: no-broken-algorithms
    description: "Deny broken cryptographic algorithms"
    severity: critical
    action: fail
    condition:
      deny_algorithms: ["md5", "sha1", "des", "3des", "rc4"]

  - id: no-ecb-mode
    description: "Deny ECB mode — no semantic security"
    severity: high
    action: fail
    condition:
      deny_modes: ["ecb"]

  - id: rsa-min-key-size
    description: "RSA keys must be at least 2048 bits"
    severity: high
    action: fail
    condition:
      algorithm: "rsa"
      min_key_size: 2048

  - id: quantum-vulnerable-warning
    description: "Warn on quantum-vulnerable algorithms"
    severity: medium
    action: warn
    condition:
      deny_quantum_status: ["quantum-vulnerable"]
`

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Scaffold .cradar.yml and policy.cradar.yml in the current directory",
	Long: `Create starter .cradar.yml and policy.cradar.yml files with commented defaults.

Refuses to overwrite existing files unless --force is given, so running
'cradar init' in an already-configured repo is a safe no-op.`,
	Args: cobra.NoArgs,
	RunE: runInit,
}

func init() {
	initCmd.Flags().Bool("force", false, "overwrite existing .cradar.yml / policy.cradar.yml")
	initCmd.Flags().String("dir", ".", "directory to scaffold into")
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, _ []string) error {
	force, _ := cmd.Flags().GetBool("force")
	dir, _ := cmd.Flags().GetString("dir")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}

	files := []struct {
		name     string
		template string
	}{
		{".cradar.yml", cradarYMLTemplate},
		{"policy.cradar.yml", policyYMLTemplate},
	}
	for _, f := range files {
		path := filepath.Join(dir, f.name)
		if !force {
			if _, err := os.Stat(path); err == nil {
				return ExitErrorf(ExitConfig,
					"%s already exists; rerun with --force to overwrite", path)
			}
		}
		if err := os.WriteFile(path, []byte(f.template), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
		fmt.Fprintf(cmd.ErrOrStderr(), "wrote %s\n", path)
	}
	return nil
}
