apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cipherradar-scanner-worker
  namespace: cipherradar-prod
  labels:
    app.kubernetes.io/name: cipherradar
    app.kubernetes.io/component: scanner-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-cipherradar-scanner-worker
  minReplicas: 2
  maxReplicas: 16
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
