apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cipherradar.fullname" . }}
  namespace: {{ include "cipherradar.namespace" . }}
  labels:
    {{- include "cipherradar.labels" . | nindent 4 }}
data:
  CRADAR_REDIS_URL: {{ include "cipherradar.redisUrl" . | quote }}
  CRADAR_DATABASE_URL: {{ include "cipherradar.databaseUrl" . | quote }}
  {{- if .Values.externalS3.endpoint }}
  CRADAR_S3_ENDPOINT: {{ .Values.externalS3.endpoint | quote }}
  {{- end }}
  {{- if .Values.externalS3.bucket }}
  CRADAR_S3_BUCKET: {{ .Values.externalS3.bucket | quote }}
  {{- end }}
